language: generic
services:
- docker
after_success:
- "./build.sh rpi_2"
- "./build.sh rpi_3"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VYSsOGC3zOsKXb9m0U6EVQuk25Fvzqg7GZOjq8Tdzy09GJjnY/NgRQ5pIepAedB8//NT0pZj0vRTzvjWkAj1RDKdhtc5VPim4gvKvKrOLyt72NP0q8q9LZqwbqAnsn/x9UAH0M+JFEng0FrC9QNmJTBbWkc0IdwOoNTfhewQVRDrfO39zziBbxPI9QKs6fAMPpN6Te6d34FaYyB7RVAnUug09iFd/hjHtTFVtwmtTTUJDbTTNzdhmp598uHL+HcLdTpgAvLZdHN8psSoLIXB+hsIFaWlMZMRKAgR8mPqQURUBBo3XH+3r5abmPRy5mumWeofIuBxFNvqO5XunMADLxWkJnt0rvsqmq3oNFf2ymVeXTN3KFnVu4ib6D5RdNhqm2IX5e+21pcUD9YI13xxEbLLFrlEEBYF7KkBZYuHXdQdWhIk1e67YgmdVvIa7CumHES9f/x9qtQ0Yr2JkWv2fUPctbvIWeS3CCv4fZsTWcccv0ystFqkmY98mDkvk2ds9ZOe+TvbunihzAIz2NSgjXlMpjMA9JZtzqdI384FTDMJgd6hbSZYLbRsB/K+Pl2Gs+0+RUZd/Mujvo/ZroWv/0xav/24C2EbaWSe1vZWeMEEManZ0rcHIu901rKt0yyyLpMKp/VrmIiVMMW2LX7ZDICE1PmM6Uqpi8UnVqQr7tw=
  file:
  - "u-boot.rpi_2.bin"
  - "u-boot.rpi_3.bin"
  on:
    tags: true
